-- 工单持久化（PostgreSQL + Flyway 管理 schema 版本）
CREATE TABLE tickets (
    id          BIGINT PRIMARY KEY,
    session_id  VARCHAR(64)  NOT NULL DEFAULT '',
    title       VARCHAR(255) NOT NULL,
    category    VARCHAR(32)  NOT NULL,
    priority    VARCHAR(16)  NOT NULL,
    status      VARCHAR(16)  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS tickets_id_seq START 1;

CREATE TABLE ticket_actions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id   BIGINT NOT NULL REFERENCES tickets (id) ON DELETE CASCADE,
    action      VARCHAR(255) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_tickets_session ON tickets (session_id);
CREATE INDEX idx_tickets_status ON tickets (status);
CREATE INDEX idx_actions_ticket ON ticket_actions (ticket_id);
